### PR TITLE
fix(bootstrap) : fix update loop

### LINKED ISSUE #3616: Bootstrap : SIGINT signal
On testnet_20 when i send SIGINT to my node he take some times to start interrupt himself. (config.bootstrap.cache_duration)

image

It is necessary to split the list updater and stop signal receiver.

### PR DESCRIPTION
**Pull request by modship**
* [X] document all added functions
* [X] try in sandbox /simulation/labnet
* [X] unit tests on the added/changed features
  * [X] make tests compile
  * [X] make tests pass 
* [X] add logs allowing easy debugging in case the changes caused problems
* [X] if the API has changed, update the API specification

fix #3616

### CODE REVIEW

File: massa-bootstrap/src/server.rs [hunk 1]
```diff
@@ -63,14 +65,15 @@ use crate::{
 /// Abstraction layer over data produced by the listener, and transported
 /// over to the worker via a channel
 type BsConn = (Duplex, SocketAddr);
+
 /// handle on the bootstrap server
 pub struct BootstrapManager {
-    update_handle: std::thread::JoinHandle<Result<(), Box<BootstrapError>>>,
```
Comment (Ben-PH) [inline massa-bootstrap/src/server.rs:68]: While in the process of moving over to native threads and de-asyncing the code-base, I would like to be absolutely explicit about which threads are being used. Might be good to remove the std::thread import, actually.

File: massa-bootstrap/src/server.rs [hunk 2]
```diff
@@ -224,23 +227,18 @@ impl BootstrapServer<'_> {
...
-            match stopper.try_recv() {
-                Ok(()) => return Ok(()),
-                Err(e) => match e {
-                    crossbeam::channel::TryRecvError::Empty => {}
-                    crossbeam::channel::TryRecvError::Disconnected => {
-                        return Err(BootstrapError::GeneralError(
-                            "update stopper unexpected disconnect".to_string(),
-                        )
-                        .into());
+            select! {
```
Comment (Ben-PH) [inline massa-bootstrap/src/server.rs:233]:
```suggestion
            crossbeam::select! {
```
Similar in principal to the thread comment

File: massa-bootstrap/src/server.rs [hunk 3]
```diff
@@ -224,23 +227,18 @@ impl BootstrapServer<'_> {
...
+                recv(stopper) -> res => {
+                    match res {
+                        Ok(()) => return Ok(()),
+                        Err(e) => return Err(Box::new(BootstrapError::GeneralError(format!("update stopper error : {}", e)))),
                     }
                 },
+                recv(ticker) -> _ => {list.update()?;},
```
Comment (Ben-PH) [inline massa-bootstrap/src/server.rs:240]: add a try_recv on the stopper here: if both are ready, then it's not guaranteed that it will choose the stopper.

In this scenario, the reality is that it's almost never gonna happen. The value will be more in self-documenting the code: "if we _can_ recieve on the stopper, that takes ultimate priority"

**Review by Ben-PH — CHANGES_REQUESTED** [review]
Nicely done, thanks!

Keeping the namespace use is a bit ugly, but is intended to help with the cognitive load for the de-async stuff: much less need to think about _which_ libraries thread/sender/selector is in play. Once the system is settled into being sync, they can be cleaned up.

**Comment by Ben-PH** [comment]
It will feel sluggish and frustrating to users. From a "perceived quality" basis I think there's a strong argument to have it in testnet_20, or at least a 20.1 bump

File: massa-bootstrap/src/server.rs (hunk 1 above)
Comment (modship) [reply massa-bootstrap/src/server.rs:68]: I can put them back but my ide displays warnings

File: massa-bootstrap/src/server.rs [hunk 4]
```diff
@@ -63,14 +65,15 @@ use crate::{
...
+
 /// handle on the bootstrap server
 pub struct BootstrapManager {
-    update_handle: std::thread::JoinHandle<Result<(), Box<BootstrapError>>>,
+    update_handle: thread::JoinHandle<Result<(), Box<BootstrapError>>>,
     // need to preserve the listener handle up to here to prevent it being destroyed
-    _listen_handle: std::thread::JoinHandle<Result<Result<(), BsConn>, Box<BootstrapError>>>,
-    main_handle: std::thread::JoinHandle<Result<(), Box<BootstrapError>>>,
-    listen_stopper_tx: crossbeam::channel::Sender<()>,
-    update_stopper_tx: crossbeam::channel::Sender<()>,
```
[the remark this answers is not in the document]
Comment (modship) [reply massa-bootstrap/src/server.rs:73]: same

File: massa-bootstrap/src/server.rs (hunk 3 above)
Comment (modship) [reply massa-bootstrap/src/server.rs:240]: in fact, priority is not specialy needed here. it's better but not needed. 
it's works well for now and there is no more waiting time for stop

**Comment by modship** [comment]
> Is it mandatory to merge this for testnet_20 ? Or it could wait 21 ?

i think it is better if it's merge for testnet_20.
That fix SIGINT && node_stop command from massa-client too

File: massa-bootstrap/src/server.rs (hunk 3 above)
Comment (Ben-PH) [reply massa-bootstrap/src/server.rs:240]: reasonably put. resolved.

File: massa-bootstrap/src/server.rs (hunk 1 above)
Comment (Ben-PH) [reply massa-bootstrap/src/server.rs:68]: Given the value of the suggested change assumes it doesn't affect the ergonomics for others (aside from the fact that it's a bit ugly in the meantime) it's better to move things towards being nice in the general case, rather than making things nice for my specific use-case.

Happy with the changes you made, given your explanation. Thanks!

**Review by Ben-PH — APPROVED** [review]
Thanks for the follow-ups, and well done on the feature, I think it'll do a lot for user experience in the testnet.

**Comment by AurelienFT** [comment]
Ok you can merge it then. It doesn't seems to modify too important things
