### PR TITLE
Fix success message bootstrap on server side

### LINKED ISSUE #2731: Bootstrap issue
Server:

```
2022-06-24T19:33:03.198953Z DEBUG massa_bootstrap::server: bootstrap serving error for peer XXXXXXXXX:40630: io error: early eof
```

Client:

```
2022-06-24T19:33:02.704317Z  INFO massa_bootstrap::client: Start bootstrapping from XXXXXXXXXXX:31245
2022-06-24T19:33:03.150430Z DEBUG massa_bootstrap::client: Received ledger batch from None to Some(
    Some(
        A12RTRgH1rQHi289AW6AkrLS9MNsNDLdvgZehEbPtRHs93h5phnc,
    ),
), an async pool batch from None to None a batch of ledger changes of size 0 and a batch of async pool changes of size 0. for slot: Slot {
    period: 0,
    thread: 31,
}
Received ledger batch from None to Some(
    Some(
        A12RTRgH1rQHi289AW6AkrLS9MNsNDLdvgZehEbPtRHs93h5phnc,
    ),
), an async pool batch from None to None a batch of ledger changes of size 0 and a batch of async pool changes of size 0. for slot: Slot {
    period: 0,
    thread: 31,
}
2022-06-24T19:33:03.192740Z  INFO massa_bootstrap::client: Successful state bootstrap
```
Config files: [files.zip](https://github.com/massalabs/massa/files/8980279/files.zip)

### PR DESCRIPTION
**Pull request by AurelienFT**
Fix #2731

### CODE REVIEW

File: massa-bootstrap/src/server.rs [hunk 1]
```diff
@@ -432,7 +432,10 @@ async fn manage_bootstrap(
     loop {
         match tokio::time::timeout(bootstrap_settings.read_timeout.into(), server.next()).await {
             Err(_) => return Ok(()),
-            Ok(Err(e)) => return Err(e),
+            Ok(Err(e)) => match e {
+                BootstrapError::IoError(_) => return Ok(()),
```
Comment (damip) [inline massa-bootstrap/src/server.rs:436]: why is IoError OK ?

Comment (AurelienFT) [reply massa-bootstrap/src/server.rs:436]: The client doesn't send a message when the bootstrap is finish he just end the socket and the server doesn't manage any client state so the server can't know that a bootstrap is well performed, he can know that steps independently are performed. It's our design choice. So the only way the server can assume the client bootstrapped it's when he disconnect. Of course, the client can disconnect when he just have connection problem but I don't think it will yield the same error and if it the case then the server has no way to know if it's in case of an end or disconnection.

File: massa-bootstrap/src/server.rs [hunk 2]
```diff
@@ -432,7 +432,10 @@ async fn manage_bootstrap(
     loop {
         match tokio::time::timeout(bootstrap_settings.read_timeout.into(), server.next()).await {
```
Comment (damip) [inline massa-bootstrap/src/server.rs:433]: so at every loop iteration we expect a timeout here ? Doesn't this slow things down a lot ?

Comment (AurelienFT) [reply massa-bootstrap/src/server.rs:433]: No we don't except a timeout at every loop iteration. We wait for a message and manage it if we timeout then we stop the connection.

File: massa-bootstrap/src/server.rs (hunk 1 above)
Comment (damip) [reply massa-bootstrap/src/server.rs:436]: Do you think we could imagine adding a client message confirming successful bootstrap before disconnecting, just like we do for errors ?

File: massa-bootstrap/src/server.rs (hunk 2 above)
Comment (damip) [reply massa-bootstrap/src/server.rs:433]: yes you're right :)

File: massa-bootstrap/src/server.rs (hunk 1 above)
Comment (AurelienFT) [reply massa-bootstrap/src/server.rs:436]: Personally I prefer with an end message, yes. But I understood that we want to have a server that just answer to ask of client and when it don't ask anything then well we disconnect him.

Comment (AurelienFT) [reply massa-bootstrap/src/server.rs:436]: Ok I do it.

Comment (AurelienFT) [reply massa-bootstrap/src/server.rs]: Done @damip

File: massa-bootstrap/src/client.rs [hunk 3]
```diff
@@ -278,25 +279,35 @@ async fn bootstrap_from_server(
...
+                    )
+                    .into()),
+                    Ok(Err(e)) => Err(e),
+                    Ok(Ok(_)) => Ok(()),
+                }?;
                 break;
             }
-            Some(BootstrapClientMessage::BootstrapError { error: _ }) => {
+            BootstrapClientMessage::BootstrapError { error: _ } => {
                 panic!("Should never happens")
```
Comment (damip) [inline massa-bootstrap/src/client.rs:306]: let's make a more explicit panic message :)

File: massa-bootstrap/src/server.rs [hunk 4]
```diff
@@ -486,6 +486,7 @@ async fn manage_bootstrap(
                         Ok(Ok(_)) => Ok(()),
                     }?;
                 }
+                BootstrapClientMessage::BootstrapSuccess => return Ok(()),
```
Comment (damip) [inline massa-bootstrap/src/server.rs:489]: I think the server should print that the bootstrap succeeded

Comment (damip) [reply massa-bootstrap/src/server.rs:489]: So the BootstrapSuccess message is basically ignored server-side ?

Comment (AurelienFT) [reply massa-bootstrap/src/server.rs:489]: No it return from this function and go back to the upper scope which print.

Comment (damip) [reply massa-bootstrap/src/server.rs:489]: okay

**Review by damip — APPROVED** [review]
Good work !

**Comment by damip** [comment]
bros merge

**Comment by damip** [comment]
bors merge
