### PR TITLE
Fix event cache estimation for slot filters

### LINKED ISSUE #4816: Massa event cache key ident estimation can be optimized
In case we query events with a filter with slot_start that is after the slot of the last event in the db, the `slots_since` function returns an Err() variant and we have the following WARN:

```
2025-01-10T13:56:05.906052Z  WARN massa_event_cache::event_cache: Could not estimate count for key indent: Event - filter_item: SlotStart(Slot { period: 2014222, thread: 15 }): period overflow error
```

In that case, we also return `max_entry_count` as the estimate.

In that specific case, we want the estimation to return 0 instead (because we have no events in the given period) to avoid unnecessary work.

### PR DESCRIPTION
**Pull request by Leo-Besancon**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by Leo-Besancon** [comment]
Todo: unit test these changes

File: massa-event-cache/src/event_cache.rs [hunk 1]
```diff
@@ -677,21 +677,26 @@ impl EventCache {
     ) -> Result<u64, ModelsError> {
         match filter_item {
             FilterItem::SlotStart(start) => {
-                let diff = self.last_slot.slots_since(start, self.thread_count)?;
+                let diff = self
+                    .last_slot
+                    .slots_since(start, self.thread_count)
+                    .unwrap_or(0);
```
Comment (sydhds) [inline massa-event-cache/src/event_cache.rs:683]: Add a small comment here explaining why we set to 0?

**Review by sydhds — CHANGES_REQUESTED** [review]

File: massa-event-cache/src/event_cache.rs (hunk 1 above)
Comment (Leo-Besancon) [reply massa-event-cache/src/event_cache.rs]: Updated with comment and unit test!

**Review by sydhds — APPROVED** [review]
All good
