### PR TITLE
Fix: `wallet_remove_addresses` does not update wallet file

### LINKED ISSUE #2172: `wallet_remove_addresses` does not update wallet file
1. `wallet_generate_private_key`
2. `wallet_remove_addresses xxxx`
3. `exit`
4. Launch client again
5. `wallet_info` address is still there!

### PR DESCRIPTION
**Pull request by AurelienFT**
I have fixed by calling `save()`. `save()` can fail with a Result so I changed the return type to be able to propagate the error.

Fix #2172.

### CODE REVIEW

File: massa-client/src/cmds.rs [hunk 1]
```diff
@@ -471,11 +471,11 @@ impl Command {
                 let mut res = "".to_string();
                 for key in parse_vec::<Address>(parameters)?.into_iter() {
                     match wallet.remove_address(key) {
-                        Some(_) => {
+                        Ok(_) => {
                             res.push_str(&format!("Removed address {} from the wallet\n", key));
                         }
-                        None => {
```
Comment (damip) [inline massa-client/src/cmds.rs:477]: let's keep this branch with `Err(MissingKeyError(_)) => res.push_str(&format!("Address {} wasn't in the wallet\n", key))` because it's a common error that needs proper formatting

File: massa-wallet/src/lib.rs [hunk 2]
```diff
@@ -77,8 +77,9 @@ impl Wallet {
         }
     }
 
-    pub fn remove_address(&mut self, address: Address) -> Option<(PublicKey, PrivateKey)> {
-        self.keys.remove(&address)
+    pub fn remove_address(&mut self, address: Address) -> Result<(), WalletError> {
+        self.keys.remove(&address).ok_or(WalletError::MissingKeyError(address))?;
+        self.save()
     }
```
Comment (damip) [inline massa-wallet/src/lib.rs:84]: also need to run "cargo fmt" before pushing for sanity

**Review by damip — CHANGES_REQUESTED** [review]

File: massa-wallet/src/lib.rs (hunk 2 above)
Comment (damip) [reply massa-wallet/src/lib.rs:84]: otheerwise, all good !

Comment (AureliaDolo) [reply massa-wallet/src/lib.rs:84]: You can set up you code editor to run cargo fmt on save

Comment (AurelienFT) [reply massa-wallet/src/lib.rs:86]: Yes I have made it but only on the massa_client subfolder. Done.

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
bors merge
