### PR TITLE
Fix infinite tester con

### LINKED ISSUE #3937: Avoid launching infinite tester connections
Currently, we have an number X of testers that launch tests. The problem is that they are using a new instance of peernet to do. This makes their connexion to test launched in a different thread each time we call `try_connect()`.

The tester should now make the test directly on his thread to block. We need to remove the usage of peernet and place the code that test the peer in the same thread as the tester.

### PR DESCRIPTION
**Pull request by modship**
* [ ] document all added functions
* [x] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

close #3937

### CODE REVIEW

File: massa-protocol-worker/src/handlers/peer_handler/tester.rs [hunk 1]
```diff
@@ -244,12 +400,19 @@ impl Tester {
         .spawn(move || {
             let db = peer_db.clone();
             let active_connections = active_connections.clone();
-            let config = PeerNetConfiguration::default(
+            let _config = PeerNetConfiguration::default(
```
Comment (AurelienFT) [inline massa-protocol-worker/src/handlers/peer_handler/tester.rs:403]: Remove this variable

File: massa-protocol-worker/src/handlers/peer_handler/tester.rs [hunk 2]
```diff
@@ -376,11 +554,21 @@ impl Tester {
...
+
+                        let res = Tester::tcp_handshake(
+                            messages_handler.clone(),
+                            db.clone(),
+                            announcement_deser.clone(),
+                            VersionDeserializer::new(),
                             listener,
-                            protocol_config.timeout_connection.to_duration(),
-                            &OutConnectionConfig::Tcp(Box::new(TcpOutConnectionConfig::new(protocol_config.read_write_limit_bytes_per_second / 10, Duration::from_millis(100)))),
+                            protocol_config.version.clone(),
```
Comment (AurelienFT) [inline massa-protocol-worker/src/handlers/peer_handler/tester.rs:564]: Some clippy warns

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge
