### PR TITLE
Fix memory leaks in the execution

### LINKED ISSUE #2488: SC ledger is different from one node to the other
Steps to reproduce:
- Upload a smart-contract
- `get_addresses` on the SC address on different nodes

Below are screenshots of my local node used to upload the SC, labnet1 and labnet2. One of the labnet has the datastore entry empty while the other has the right value...

Screenshot 2022-04-02 at 11 09 35
Screenshot 2022-04-02 at 11 09 46
Screenshot 2022-04-02 at 11 09 23

Maybe related: https://github.com/massalabs/massa/issues/2487

### PR DESCRIPTION
**Pull request by AurelienFT**
Fix #2488 and add the sorting of events by `index_in_slot`.

### CODE REVIEW

File: massa-execution-worker/src/tests/scenarios_mandatories.rs [hunk 1]
```diff
@@ -98,6 +99,91 @@ fn test_sending_read_only_execution_command() {
...
 }
 
+/// Test the gas usage in nested calls using call sc operation
+///
+/// Create a smart contract and send it in the blockclique.
+/// This smart contract have his sources in the sources folder.
+/// It calls the test function that have a sub-call to the receive function and send it to the blockclique.
+/// We are checking that the gas is going down through the execution even in sub-calls.
+///
+/// This test can fail if the gas is going up in the execution
```
Comment (Eitu33) [inline massa-execution-worker/src/tests/scenarios_mandatories.rs:109]: Maybe add something explaining that gas going up probably means that sub calls subs were not taken in account.

**Review by damip — APPROVED** [review]

File: massa-execution-worker/src/tests/scenarios_mandatories.rs (hunk 1 above)
Comment (Eitu33) [reply massa-execution-worker/src/tests/scenarios_mandatories.rs:109]: Ok maybe not.

**Review by Eitu33 — APPROVED** [review]

**Comment by Eitu33** [comment]
bors merge
