### PR TITLE
Fix vesting file (old timestamp)

### LINKED ISSUE #3651: Node panic on boot (SANDBOX)
Node crash on startup (SANDBOX) : 

image

Caused by unwrap and get_latest_block_slot_at_timestamp() used with a passed timestamp

### PR DESCRIPTION
**Pull request by modship**
* [X] document all added functions
* [X] try in sandbox /simulation/labnet
* [X] unit tests on the added/changed features
  * [X] make tests compile
  * [X] make tests pass 
* [X] add logs allowing easy debugging in case the changes caused problems
* [X] if the API has changed, update the API specification

Fix #3651

### CODE REVIEW

File: massa-execution-worker/src/execution.rs [hunk 1]
```diff
@@ -1470,16 +1470,25 @@ impl ExecutionState {
...
-                        prev.end_slot = next_range_slot.get_prev_slot(config.thread_count)?;
+                        if let Some(next_range_slot) =
+                            get_slot_at_timestamp(config, next.timestamp)?
+                        {
+                            prev.end_slot = next_range_slot.get_prev_slot(config.thread_count)?;
+                        }
 
                         Ok(prev)
                     })
+                    // we don't need range with StartSlot(0,0) && EndSlot(0,0)
```
Comment (AurelienFT) [inline massa-execution-worker/src/execution.rs:1486]: We need the range with the start timestamp at genesis otherwise from genesis to X there is no vesting.

Comment (AurelienFT) [reply massa-execution-worker/src/execution.rs:1486]: No problem.

**Review by AurelienFT — APPROVED** [review]
Nice fix
