### PR TITLE
Deferred call / async msg context error

### LINKED ISSUE #4868: Deferred call context error
When the execution of the deferred call fail we need more information about the fail in the event generated in the context of the caller SC.

### PR DESCRIPTION
**Pull request by modship**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by damip** [comment]
Also CI error

**Comment by Leo-Besancon** [comment]
> Isn't the event emission redundant with the one that happens in reset_to_snapshot ?

Indeed, in sandbox I have both errors:
```
Context: Slot: (period: 20, thread: 1) at index: 0
On chain execution
Block id: B1A5geiKTRVmUzMULEtHS12nNCyn61Fq4uKrSdmRymFH1bShJgP
Call stack: AU1CCxYnttgXg4dWn1ADh4z4scXX7JreYPE9EEkM2FMroREQAMfA,AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV

Data: {"massa_execution_error":"Runtime error: The called smart contract address AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV does not exist"}

Context: Slot: (period: 20, thread: 1) at index: 0
On chain execution
Block id: B1A5geiKTRVmUzMULEtHS12nNCyn61Fq4uKrSdmRymFH1bShJgP
Call stack:

Data: DeferredCall execution fail call_id: D13Bi6HjbQbzue4Rurp6MEHRMDaQmH4piVqK1QgFq16FJsG8iMNm1DqNNJau3VwqL  |  Error: Runtime error: The called smart contract address AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV does not exist
 DeferredCall { sender_address: AU1CCxYnttgXg4dWn1ADh4z4scXX7JreYPE9EEkM2FMroREQAMfA, target_slot: Slot { period: 20, thread: 1 }, target_address: AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV, target_function: "receive", parameters: [], coins: 0.000001, max_gas: 10000000, fee: 0.0366, cancelled: false }

```

I think the best way to handle it would be to update the reset_to_snapshot context to reference the DeferredCall (and potentially do the same for ASCs), to improve debugging.

**Comment by damip** [comment]
> > Isn't the event emission redundant with the one that happens in reset_to_snapshot ?
> 
> Indeed, in sandbox I have both errors:
> 
> ```
> Context: Slot: (period: 20, thread: 1) at index: 0
> On chain execution
> Block id: B1A5geiKTRVmUzMULEtHS12nNCyn61Fq4uKrSdmRymFH1bShJgP
> Call stack: AU1CCxYnttgXg4dWn1ADh4z4scXX7JreYPE9EEkM2FMroREQAMfA,AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV
> 
> Data: {"massa_execution_error":"Runtime error: The called smart contract address AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV does not exist"}
> 
> Context: Slot: (period: 20, thread: 1) at index: 0
> On chain execution
> Block id: B1A5geiKTRVmUzMULEtHS12nNCyn61Fq4uKrSdmRymFH1bShJgP
> Call stack:
> 
> Data: DeferredCall execution fail call_id: D13Bi6HjbQbzue4Rurp6MEHRMDaQmH4piVqK1QgFq16FJsG8iMNm1DqNNJau3VwqL  |  Error: Runtime error: The called smart contract address AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV does not exist
>  DeferredCall { sender_address: AU1CCxYnttgXg4dWn1ADh4z4scXX7JreYPE9EEkM2FMroREQAMfA, target_slot: Slot { period: 20, thread: 1 }, target_address: AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV, target_function: "receive", parameters: [], coins: 0.000001, max_gas: 10000000, fee: 0.0366, cancelled: false }
> ```
> 
> I think the best way to handle it would be to update the reset_to_snapshot context to reference the DeferredCall (and potentially do the same for ASCs), to improve debugging, and not emit another event in the deferred_call_fail_exec function

I agree with the strategy you proposed. Maybe feed an an enum "origin" to the reset function
```
enum ResetOrigin {
    DeferredCall(DeferredCallId),
    AsyncMessage(AsyncMessageID),
    Operation(OperationId),
    // autres si besoin
}
```

**Comment by modship** [comment]
> > > Isn't the event emission redundant with the one that happens in reset_to_snapshot ?
> > 
> > 
> > Indeed, in sandbox I have both errors:
> > ```
> > Context: Slot: (period: 20, thread: 1) at index: 0
> > On chain execution
> > Block id: B1A5geiKTRVmUzMULEtHS12nNCyn61Fq4uKrSdmRymFH1bShJgP
> > Call stack: AU1CCxYnttgXg4dWn1ADh4z4scXX7JreYPE9EEkM2FMroREQAMfA,AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV
> > 
> > Data: {"massa_execution_error":"Runtime error: The called smart contract address AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV does not exist"}
> > 
> > Context: Slot: (period: 20, thread: 1) at index: 0
> > On chain execution
> > Block id: B1A5geiKTRVmUzMULEtHS12nNCyn61Fq4uKrSdmRymFH1bShJgP
> > Call stack:
> > 
> > Data: DeferredCall execution fail call_id: D13Bi6HjbQbzue4Rurp6MEHRMDaQmH4piVqK1QgFq16FJsG8iMNm1DqNNJau3VwqL  |  Error: Runtime error: The called smart contract address AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV does not exist
> >  DeferredCall { sender_address: AU1CCxYnttgXg4dWn1ADh4z4scXX7JreYPE9EEkM2FMroREQAMfA, target_slot: Slot { period: 20, thread: 1 }, target_address: AS12jc7fTsSKwQ9hSk97C3iMNgNT1XrrD6MjSJRJZ4NE53YgQ4kFV, target_function: "receive", parameters: [], coins: 0.000001, max_gas: 10000000, fee: 0.0366, cancelled: false }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think the best way to handle it would be to update the reset_to_snapshot context to reference the DeferredCall (and potentially do the same for ASCs), to improve debugging, and not emit another event in the deferred_call_fail_exec function
> 
> I agree with the strategy you proposed. Maybe feed an an enum "origin" to the reset function
> 
> ```
> enum ResetOrigin {
>     DeferredCall(needed_info_on_the_deferred_call),
>     AsyncMessage(needed_info_on_the_async_msg),
>     Operation(needed_info_on_the_deferred_operation),
>     // maybe others
> }
> ```

We already have the enum `ExecutionError` in `reset_to_snapshot`, so we can do with it

File: massa-models/src/output_event.rs [hunk 1]
```diff
@@ -72,6 +79,19 @@ impl Display for EventExecutionContext {
...
+            writeln!(f, "Deferred call id: {}", id)?;
+        }
+        if let Some(id) = self.async_msg_id {
+            let serializer = AsyncMessageIdSerializer::new();
+            let mut serialized = Vec::new();
+            serializer.serialize(&id, &mut serialized).unwrap();
+            writeln!(
+                f,
+                "Async message id: {}",
+                bs58::encode(serialized).into_string()
```
Comment (Leo-Besancon) [inline massa-models/src/output_event.rs:92]: I think we should either show the tuple corresponding to the Async message id as is, or, if we want to encode it like that, we should implement it directly for the AsyncMessageId struct, in case we want to reuse it (and maybe add `ASC` prefix or something)

**Review by Leo-Besancon — APPROVED** [review]
A small non-blocking comment, and the CI needs to get fixed, but otherwise it's great!

**Review by Leo-Besancon — APPROVED** [review]
