### PR TITLE
fix massa client without grpc

### LINKED ISSUE #3998: massa-client crash on startup
run a massa client without active node with grpc causes a crash.

image

### PR DESCRIPTION
**Pull request by modship**
* [x] document all added functions
* [ ] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

close #3998

### CODE REVIEW

File: massa-sdk/src/lib.rs [hunk 1]
```diff
@@ -89,14 +89,22 @@ impl Client {
...
-        let channel = tonic::transport::Channel::from_shared(grpc_url)?
+        // try to start grpc client and connect to the server
+        let grpc_opts = match tonic::transport::Channel::from_shared(grpc_url)?
             .connect()
-            .await?;
+            .await
+        {
+            Ok(channel) => Some(MassaServiceClient::new(channel)),
+            Err(_e) => {
+                // TODO print error
```
Comment (aoudiamoncef) [inline massa-sdk/src/lib.rs:99]: We could write a small warning here "gRPC is not enabled"

File: massa-client/src/cmds.rs [hunk 2]
```diff
@@ -774,42 +774,47 @@ impl Command {
...
+                        );
+                        Ok(Box::new(()))
+                    }
                 } else {
-                    println!("Generated {} address and added it to the wallet", ad);
-                    println!(
-                        "Type `node_start_staking <address>` to start staking with this address.\n"
-                    );
-                    Ok(Box::new(()))
+                    bail!("GRPC is not enabled on this node");
```
Comment (aoudiamoncef) [inline massa-client/src/cmds.rs:817]: "gRPC is not enabled"

**Review by aoudiamoncef — APPROVED** [review]
