### PR TITLE
Fix tests pool failing

### LINKED ISSUE #3509: Intermittant failures in pool tests
**Describe the bug**
Pool tests in `massa-pool-worker` fail intermittently. It appears that the component that should be receiving the data from the mocker isn't getting the data it needs

**To Reproduce**

on testnet_20 run the following in a bash shell:

```bash
COUNTER = 0;
while cargo test test_pool -F testing --release ; do
    COUNTER=$[$COUNTER +1]
    :
done

echo $COUNTER;
```

It loops, failing with an `echo $COUNTER` output > 1 (usually

**Expected behavior**
Either a Fail where `echo $COUNTER` outputs `1`, or an infinite loop 

**Desktop (please complete the following information):**

Ubuntu, but that should only be a bash-script thing

**Additional context**
In CI this shouldn't be an issue, as our tests have up to 10 retries, and it would be incredibly rare for this to fail more than 3 or 4 times in a row.

The logic being tested seems to be correct, that is, if the code being tested is incorrect, it will always fail.

### PR DESCRIPTION
**Pull request by AurelienFT**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

The tests were failing because `add_operations` is managed in an other thread and so the tests don't wait that the ops are inserted before trying to fetch them. So sometimes it was fast enough sometimes not. With the new sleep it's always fast enough.

The `test_pool` failed after this change because it was wrong by design. Fixed it.

Fix #3509 and #3584

### CODE REVIEW

**Comment by Ben-PH** [comment]
LGTM. I'm gonna try something locally before I approve, but the essence of it is something like this:

```bash
for ((i = 0 ; i < 100 ; i++)); do
	cargo test --release #argument only for these tests here
done
```

**Comment by AurelienFT** [comment]
I will fix the tests that are not related to this PR but as it's a test fixing PR let's make everything here.

**Comment by Ben-PH** [comment]
Would it be constructive to add a comment to one of the sleeps that provides this context (not a merge-blocking suggestion)

> The tests were failing because add_operations is managed in an other thread and so the tests don't wait that the ops are inserted before trying to fetch them. So sometimes it was fast enough sometimes not. With the new sleep it's always fast enough.

**Comment by AurelienFT** [comment]
It shouldn't fail anymore will check on that also

File: massa-pool-worker/src/tests/operation_pool_tests.rs [hunk 1]
```diff
@@ -62,17 +64,15 @@ fn test_pool() {
             // generate (id, transactions, range of validity) by threads
             let mut thread_tx_lists = vec![Vec::new(); pool_config.thread_count as usize];
 
+            let mut storage = storage_base.clone_without_refs();
```
Comment (Ben-PH) [inline massa-pool-worker/src/tests/operation_pool_tests.rs:67]: Might be out of scope for this PR, but it might be helpful to think about "why clone_without_refs, and not just clone, in this particular context".

Comment (AurelienFT) [reply massa-pool-worker/src/tests/operation_pool_tests.rs:67]: Issue made #3605

**Review by Ben-PH — APPROVED** [review]
LGTM, Just apply the same comment change "Allow some time for...", and for CI to finish and merge it.
