### PR TITLE
fix doc client

### LINKED ISSUE #4410: Doc duplicated in massa_sdk ClientConfig struct
/// maximum size in bytes of a request.
    pub max_request_body_size: u32,
    /// maximum size in bytes of a response.
    pub request_timeout: MassaTime,
    /// maximum size in bytes of a response.
    pub max_concurrent_requests: usize,

### PR DESCRIPTION
**Pull request by AurelienFT**
Fix #4410

### CODE REVIEW

File: massa-sdk/src/config.rs [hunk 1]
```diff
@@ -10,7 +10,7 @@ pub struct ClientConfig {
     pub max_request_body_size: u32,
     /// maximum size in bytes of a response.
```
Comment (sydhds) [inline massa-sdk/src/config.rs:11]: Is this one correct?

**Review by sydhds — CHANGES_REQUESTED** [review]

File: massa-sdk/src/config.rs (hunk 1 above)
Comment (AurelienFT) [reply massa-sdk/src/config.rs]: Fixed.

**Review by sydhds — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge
