### PR TITLE
Fix all security input time

### LINKED ISSUE #3849: Internal Audit: Massa-Time
* [x] remove `From<u64>` and replace it with a `from_millis` method to be explicit (see https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.from_millis )
* [x]  rename to_millis into as_millis (to match the STD: https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.as_millis )
* [x] in the code, sometime we call into(), sometimes from(), sometimes MassTime(). This can be harmonized
* [x] add docs for all methods
* [x]  now() should never fail, and f it does, it's unrecoverable => so let's not bother with error handling:
```rust
    pub fn now() -> Self {
        let now_millis = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("could not get duration since UNIX_EPOCH")
            .as_millis()
            .try_into()
            .expect("could fit current time into its underlying representation");
        MassaTime::from_millis(now_millis)
    }
```

### PR DESCRIPTION
**Pull request by AurelienFT**

### CODE REVIEW

File: massa-grpc/src/public.rs [hunk 1]
```diff
@@ -43,7 +43,7 @@ pub(crate) fn execute_read_only_call(
     let caller_address = match call.caller_address {
         Some(addr) => Address::from_str(&addr)?,
         None => {
-            let now = MassaTime::now()?;
```
Comment (damip) [inline massa-grpc/src/public.rs:46]: can the error variant corresponding to this "?" be removed as well ?

File: massa-grpc/src/public.rs [hunk 2]
```diff
@@ -398,7 +398,7 @@ pub(crate) fn get_stakers(
         });
 
     // Get the current cycle and slot.
-    let now: MassaTime = MassaTime::now()?;
```
Comment (damip) [inline massa-grpc/src/public.rs:401]: can the error variant corresponding to this "?" be removed as well ?

File: massa-grpc/src/public.rs [hunk 3]
```diff
@@ -685,7 +685,7 @@ pub(crate) fn get_status(
     _request: tonic::Request<grpc_api::GetStatusRequest>,
 ) -> Result<grpc_api::GetStatusResponse, GrpcError> {
     let config = CompactConfig::default();
-    let now = MassaTime::now()?;
```
Comment (damip) [inline massa-grpc/src/public.rs:688]: can the error variant corresponding to this "?" be removed as well ?

File: massa-protocol-worker/src/handlers/endorsement_handler/retrieval.rs [hunk 4]
```diff
@@ -243,7 +243,7 @@ pub(crate) fn note_endorsements_from_peer(
     // From there we note new endorsements and propagate them
 
     // Filter out endorsements if they are too old (max age of the inclusion slot: `max_endorsements_propagation_time`)
-    let now = MassaTime::now()?;
```
Comment (damip) [inline massa-protocol-worker/src/handlers/endorsement_handler/retrieval.rs:246]: can the error variant corresponding to this "?" be removed as well ?

File: massa-time/src/lib.rs [hunk 5]
```diff
@@ -123,29 +120,7 @@ impl Deserializer<MassaTime> for MassaTimeDeserializer {
 
 impl fmt::Display for MassaTime {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
-        write!(f, "{}", self.to_millis())
-    }
-}
-
-impl TryFrom<Duration> for MassaTime {
```
Comment (damip) [inline massa-time/src/lib.rs:130]: this was never used ?

File: massa-time/src/lib.rs [hunk 6]
```diff
@@ -165,26 +140,6 @@ impl From<MassaTime> for Duration {
     }
 }
 
-impl FromStr for MassaTime {
```
Comment (damip) [inline massa-time/src/lib.rs:168]: this was also never used ?

File: massa-time/src/lib.rs [hunk 7]
```diff
@@ -415,7 +370,7 @@ impl MassaTime {
     /// assert_eq!(massa_time.format_instant(), String::from("2022-01-01T00:00:00Z"))
     /// ```
     pub fn format_instant(&self) -> String {
```
Comment (damip) [inline massa-time/src/lib.rs:372]: are there cases where we would print / format unchecked inputs ? if so, this could be a source of panic attacks

File: massa-time/src/lib.rs (hunk 6 above)
Comment (AurelienFT) [reply massa-time/src/lib.rs:168]: Used two times but changed it

File: massa-time/src/lib.rs (hunk 5 above)
Comment (AurelienFT) [reply massa-time/src/lib.rs:130]: No

File: massa-time/src/lib.rs (hunk 7 above)
Comment (AurelienFT) [reply massa-time/src/lib.rs:372]: Yes maybe it could be it's not checked anywhere but it wasn't on the security team input issue will look into it after.

File: massa-grpc/src/private.rs [hunk 8]
```diff
@@ -228,7 +228,7 @@ pub(crate) fn get_node_status(
     _request: tonic::Request<grpc_api::GetNodeStatusRequest>,
 ) -> Result<grpc_api::GetNodeStatusResponse, GrpcError> {
     let config = CompactConfig::default();
-    let now = MassaTime::now()?;
```
[the remark this answers is not in the document]
Comment (AurelienFT) [reply massa-grpc/src/private.rs:231]: Done

File: massa-grpc/src/public.rs (hunk 1 above)
Comment (AurelienFT) [reply massa-grpc/src/public.rs:46]: Done

File: massa-grpc/src/public.rs (hunk 2 above)
Comment (AurelienFT) [reply massa-grpc/src/public.rs:401]: Done

File: massa-grpc/src/public.rs (hunk 3 above)
Comment (AurelienFT) [reply massa-grpc/src/public.rs:688]: Done

File: massa-protocol-worker/src/handlers/endorsement_handler/retrieval.rs (hunk 4 above)
Comment (AurelienFT) [reply massa-protocol-worker/src/handlers/endorsement_handler/retrieval.rs:246]: No, used [here](https://github.com/massalabs/massa/blob/5f46612d74b4080ffeb83878b7e17f40b8c8d7fa/massa-protocol-worker/src/handlers/block_handler/retrieval.rs#L931) and [here](https://github.com/massalabs/massa/blob/b4e352543ddd75a82c9ca78fbc8ce548d951c04a/massa-protocol-worker/src/handlers/operation_handler/retrieval.rs#L256)

File: massa-time/src/lib.rs (hunk 7 above)
Comment (damip) [reply massa-time/src/lib.rs:372]: ok, can we open a followup issue on this ?

Comment (AurelienFT) [reply massa-time/src/lib.rs:372]: I have made the change just now. Tell me if it's good for you :) !

**Review by Leo-Besancon — APPROVED** [review]

File: massa-time/src/lib.rs (hunk 7 above)
Comment (damip) [reply massa-time/src/lib.rs:372]: sounds good :)

**Review by damip — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge
